version: '3'

services:
  hole-fw:
    image: hole-fw:0.2.1-beta.0
    container_name: hole-fw
    ports:
      - "9393:9393"
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: "dev"