version: '3'

services:
  hole-fw:
    image: hole-fw:0.1.0-beta.0
    container_name: hole-fw
    ports:
      - "9193:9193"
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: "dev"